#!/usr/bin/env bash

set -o pipefail

if [ -z ${INPUT_MOUNTPOINT} ]; then
    echo -e "No mountpoint was provided"
    exit 1
fi

exit_code=0
curl -LOJs https://raw.githubusercontent.com/seqsense/ros_style/master/.clang-format
trap 'rm -f ~/.clang-format' EXIT

paths_to_ignore=$(find ${INPUT_MOUNTPOINT} -type f -not -path '*/build/*' -name ".lint-ignore" | xargs dirname)

find_command="find ${INPUT_MOUNTPOINT} \( "
for path in ${paths_to_ignore[@]}; do
    find_command+=" -path '${path}' -o "
done
find_command+=" -path '*/build/*' \) -prune -o \( -name '*.hpp' -o -name '*.cpp' -o -name '*.h' \) -print"

files_to_check=($(eval "${find_command}"))
echo "Running $(basename ${0}) on ${#files_to_check[@]} source file(s) ..."
if [ -z "${files_to_check}" ]; then
    echo " - Found 0 source file(s)"
    echo -e " - [\e[32mPASSED\e[0m]"
    exit 0
fi
for file in ${files_to_check[@]}; do
    filename_without_mountpoint=${file#${INPUT_MOUNTPOINT}/}
    cat ${file} | clang-format-11 --style=file --output-replacements-xml - |
        grep -q "<replacement " &&
        echo -e "[\e[31mFAILED\e[0m]: ${filename_without_mountpoint}"
    if [ $? -eq 0 ]; then
        exit_code=1
        cat ${file} | clang-format-11 --style=file >/tmp/formatted_file
        diff --color -u ${file} /tmp/formatted_file
    fi
done

exit ${exit_code}
