#!/usr/bin/env bash

set -eo pipefail

cd /mnt
files_to_check=$(find . -type f -not -path '*/\.git/*' -not -path '*/__pycache__/*' -not -path '*/\.mypy_cache/*')

exit_code=0

for file in ${files_to_check}; do
    filetype=$(file -b --mime-type ${file})
    if echo ${filetype} | grep -qE "text/x-python|text/x-script.python"; then
        flake8 --count --show-source --statistics --config=${HOME}/.flake8 ${file} |
            sed 's|^\(\S\+\):\([0-9]\+\):\([0-9]\+\): \(.*\)$|::error file=\1,line=\2,col=\3::\4\n\0|'
        exit_code=$(($exit_code | ${PIPESTATUS[0]}))
    fi
done

if [ ${exit_code} -eq 0 ]; then
    echo "passed=true"
else
    echo "passed=false"
fi

exit ${exit_code}
