#!/usr/bin/env bash

set -eo pipefail

cd /mnt
files_to_check=$(find . -type f -not -path '*/build/*' -name "*.cpp" -o -name "*.h" -o -name "*.hpp")

if [ -z "${files_to_check}" ]; then
    echo "found 0 source file(s)"
    echo "passed=true"
    exit 0
fi
(
    roslint-cpplint \
        --filter=-runtime/references,-build/c++11 --headers=h,hpp \
        ${files_to_check} \
        2>&1 >/dev/null |
        sed 's/^\([^:]\+\):\([0-9]\+\):\s\+\(.*\)/::error file=\1,line=\2::\3/'
) && echo "passed=true" ||
    (
        echo "passed=false"
        exit 1
    )
