#!/usr/bin/env bash

set -eo pipefail

exit_code=0
linters=(
    code-lint-clang
    code-lint-flake8
    code-lint-roslint
    # code-lint-typecheck
)
for check in ${linters[@]}; do
    echo "Running ${check}"
    if ! ${check}; then
        exit_code=1
        echo "failed ${check}"
    fi
done

exit ${exit_code}
