#!/usr/bin/env bash

set -eo pipefail

exit_code=0
linters=(
    code-lint-clang
    code-lint-flake8
    code-lint-roslint
    # code-lint-typecheck
)
for check in ${linters[@]}; do
    if ! ${check}; then
        exit_code=1
    fi
done
if [ ${exit_code} -eq 0 ]; then
    echo -e "All tests passed"
else
    echo -e "One or more test(s) failed"
fi
exit ${exit_code}
