#!/usr/bin/env bash

echo "Running $(basename ${0}) ..."

set -eo pipefail

cd /mnt/input

paths_to_ignore=$(find . -type f -not -path '*/build/*' -name ".lint-ignore" | xargs -r dirname)

find_command="find . -type f -not -path '*/build/*'"
for path in ${paths_to_ignore}; do
    find_command="${find_command} -not -path '${path}/*'"
done
find_command="${find_command} \( -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \)"

files_to_check=($(eval "${find_command}"))
files_that_differ=()

if [ -z "${files_to_check}" ]; then
    echo " - Found 0 source file(s)"
    echo -e " - [\e[32mPASSED\e[0m]"
    exit 0
fi
(
    echo " - Found ${#files_to_check[@]} source file(s)"
    passed=true
    for file in "${files_to_check[@]}"; do
        path_output=/mnt/output/sq-clang/${file}
        dir_output=$(dirname ${path_output})
        mkdir -p ${dir_output}
        clang-format-11 --style=file --Werror "$file" > ${path_output}
        if ! diff -q "${file}" ${path_output}; then
            echo -e "\e[31mDIFFERENCES FOUND\e[0m in ${file}"
            diff "$file" "${path_output}"
            echo ""
            echo "----"
            echo ""
            passed=false
        fi
    done
    return $passed
) && echo -e " - [\e[32mPASSED\e[0m]" ||
    (
        echo -e " - [\e[31mFAILED\e[0m] Some file(s) require formatting"
        echo -e " - [\e[34m TIP! \e[0m] View the diff using meld by running: meld . /tmp/code-linting-bbq/sq-clang"
        echo ""
        exit 1
    )
