#!/usr/bin/env bash

echo "Running $(basename ${0}) ..."

set -eo pipefail

cd /mnt/input

curl -LOJs https://raw.githubusercontent.com/seqsense/ros_style/master/mypy.ini
trap 'rm -f mypy.ini' EXIT

cmd="mypy --config-file mypy.ini --scripts-are-modules"

files_to_check=$(find . -type f -not -path '*/\.git/*' -not -path '*/__pycache__/*' -not -path '*/\.mypy_cache/*')

python_files=()

for file in ${files_to_check}; do
    filetype=$(file -b --mime-type ${file})
    if echo ${filetype} | grep -qE "text/x-python|text/x-script.python"; then
        python_files+=(${file})
    fi
done

echo " - Found ${#python_files[@]} python file(s)"
if [ ${#python_files[@]} -eq 0 ]; then
    echo -e " - [\e[32mPASSED\e[0m]"
    exit 0
fi

# install explicitly listed type stub packages
if [ -f ".mypy-stub-pkgs" ]; then
    pip install -r .mypy-stub-pkgs
fi

# workaround to get mypy to figure out the types it should install
# note that it does not upgrade already installed packages
$(echo "${cmd} ${python_files[@]}") >/dev/null 2>/dev/null || true
mypy --install-types --non-interactive

output="$(${cmd} ${python_files[@]} | tee /dev/stderr)"
result="$(echo "${output}" | tail -n 1)"

echo "${output}" | sed -n 's|^\(\S\+\):\([0-9]\+\):\([0-9]\+\): error: \(.*\)$|::error file=\1,line=\2,col=\3::\4|p'

if [[ -n "$result" ]]; then
    error="$(echo $result | awk '/^Found/{print $2}')"
    if [[ -z "$error" ]]; then
        echo -e " - [\e[32mPASSED\e[0m]"
        exit 0
    fi
fi
echo -e " - [\e[31mFAILED\e[0m]"
exit 1
