#!/usr/bin/env bash

set -eo pipefail

exit_code=0
linters=(
    lint-sq-clang
    lint-sq-flake8
    lint-sq-roslint
    # lint-sq-typecheck
)
for check in ${linters[@]}; do
    if ! ${check}; then
        exit_code=1
    fi
done
if [ ${exit_code} -eq 0 ]; then
    echo -e "All tests passed"
else
    echo -e "One or more test(s) failed"
fi
exit ${exit_code}
