#!/usr/bin/env bash

set -eo pipefail

files_to_check=$(find ~/workspace/mounts -name "*.cpp" -o -name "*.h" -o -name "*.hpp")

(
    set -eo pipefail
    roslint-cpplint \
        --filter=-runtime/references,-build/c++11 --headers=h,hpp \
        ${files_to_check} \
        2>&1 >/dev/null |
        sed 's/^\([^:]\+\):\([0-9]\+\):\s\+\(.*\)/::error file=\1,line=\2::\3/'
) && echo "passed=true" ||
    (
        echo "passed=false"
        exit 1
    )
